// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj-sUZ6B9hh_9v-Ov7CMaE8dCQKsE4wb8',
    appId: '1:1028979844596:web:dd1918388110d336be45a1',
    messagingSenderId: '1028979844596',
    projectId: 'yomi-9d453',
    authDomain: 'yomi-9d453.firebaseapp.com',
    storageBucket: 'yomi-9d453.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkpjt12MoxWla5poDIStbvSk4G_Ng3o6Y',
    appId: '1:1028979844596:android:bea822cc20ab25f6be45a1',
    messagingSenderId: '1028979844596',
    projectId: 'yomi-9d453',
    storageBucket: 'yomi-9d453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDahqXGh-33WlX7vv542pags6XN8JX22iM',
    appId: '1:1028979844596:ios:8f934d6e9818d57abe45a1',
    messagingSenderId: '1028979844596',
    projectId: 'yomi-9d453',
    storageBucket: 'yomi-9d453.firebasestorage.app',
    iosBundleId: 'com.yomi.yomi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDahqXGh-33WlX7vv542pags6XN8JX22iM',
    appId: '1:1028979844596:ios:8f934d6e9818d57abe45a1',
    messagingSenderId: '1028979844596',
    projectId: 'yomi-9d453',
    storageBucket: 'yomi-9d453.firebasestorage.app',
    iosBundleId: 'com.yomi.yomi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj-sUZ6B9hh_9v-Ov7CMaE8dCQKsE4wb8',
    appId: '1:1028979844596:web:bc258f2e477d76acbe45a1',
    messagingSenderId: '1028979844596',
    projectId: 'yomi-9d453',
    authDomain: 'yomi-9d453.firebaseapp.com',
    storageBucket: 'yomi-9d453.firebasestorage.app',
  );
}
